# Site
title:              Jane Doe
bio:                'Science by day. Stories by night.'
description:        "I'm a second-year PhD student at X, focusing on the genetics and epigenetics of cancer. I spend half my days at the bench, and half at the computer. Prior to this, I worked in a next-generation sequencing facility. I hold a BSc in Neuroscience from Y and an MPhil in Computational Biology from the University of Cambridge. If you'd like to know more about my research you can check it out here. Outside of my research, I am an aspiring journalist with a deep interest in tech and travel. I founded the X magazine. I'm also passionate about STEM outreach and I write about science for my <a href="http://www.trinitynews.ie">university newspaper</a>"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/scipic-big.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://cobri.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            username
#facebook:           username
github:             cobri
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
